if bool(False): from app import Key, Keyboard

# VIRTUAL KEY CODES (not defined by pynput) ####################################

Keyboard.A = 0x00
Keyboard.S = 0x01
Keyboard.D = 0x02
Keyboard.F = 0x03
Keyboard.H = 0x04
Keyboard.G = 0x05
Keyboard.Z = 0x06
Keyboard.X = 0x07
Keyboard.C = 0x08
Keyboard.V = 0x09
Keyboard.B = 0x0B
Keyboard.Q = 0x0C
Keyboard.W = 0x0D
Keyboard.E = 0x0E
Keyboard.R = 0x0F
Keyboard.Y = 0x10
Keyboard.T = 0x11
Keyboard.ONE = 0x12
Keyboard.TWO = 0x13
Keyboard.THREE = 0x14
Keyboard.FOUR = 0x15
Keyboard.SIX = 0x16
Keyboard.FIVE = 0x17
Keyboard.EQUAL = 0x18
Keyboard.NINE = 0x19
Keyboard.SEVEN = 0x1A
Keyboard.DASH = 0x1B
Keyboard.EIGHT = 0x1C
Keyboard.ZERO = 0x1D
Keyboard.RIGHT_SQUARE = 0x1E
Keyboard.O = 0x1F
Keyboard.U = 0x20
Keyboard.LEFT_SQUARE = 0x21
Keyboard.I = 0x22
Keyboard.P = 0x23
Keyboard.L = 0x25
Keyboard.J = 0x26
Keyboard.APOSTROPHE = 0x27
Keyboard.K = 0x28
Keyboard.SEMICOLON = 0x29
Keyboard.BACK_SLASH = 0x2A
Keyboard.COMMA = 0x2B
Keyboard.FORWARD_SLASH = 0x2C
Keyboard.N = 0x2D
Keyboard.M = 0x2E
Keyboard.DOT = 0x2F
Keyboard.GRAVE = 0x32

# NORMAL LAYOUT ################################################################

# in_key -> (out_key, should_press_shift)
normal = Keyboard._NORMAL_LAYOUT[0]
normal[Keyboard.GRAVE] = (Keyboard.THREE, True)
normal[Keyboard.ONE] = (Keyboard.FOUR, True)
normal[Keyboard.TWO] = (Keyboard.SEVEN, True)
normal[Keyboard.THREE] = (Keyboard.EIGHT, True)
normal[Keyboard.FOUR] = (Keyboard.EQUAL, False)
normal[Keyboard.FIVE] = (Keyboard.LEFT_SQUARE, True)
normal[Keyboard.SIX] = (Keyboard.RIGHT_SQUARE, True)
normal[Keyboard.SEVEN] = (Keyboard.COMMA, True)
normal[Keyboard.EIGHT] = (Keyboard.DOT, True)
normal[Keyboard.NINE] = (Keyboard.NINE, True)
normal[Keyboard.ZERO] = (Keyboard.ZERO, True)
normal[Keyboard.DASH] = (Keyboard.LEFT_SQUARE, False)
normal[Keyboard.EQUAL] = (Keyboard.RIGHT_SQUARE, False)
normal[Keyboard.Q] = (Keyboard.APOSTROPHE, False)
normal[Keyboard.W] = (Keyboard.COMMA, False)
normal[Keyboard.E] = (Keyboard.DOT, False)
normal[Keyboard.R] = (Keyboard.P, False)
normal[Keyboard.T] = (Keyboard.Y, False)
normal[Keyboard.Y] = (Keyboard.F, False)
normal[Keyboard.U] = (Keyboard.G, False)
normal[Keyboard.I] = (Keyboard.C, False)
normal[Keyboard.O] = (Keyboard.R, False)
normal[Keyboard.P] = (Keyboard.L, False)
normal[Keyboard.LEFT_SQUARE] = (Keyboard.FORWARD_SLASH, False)
normal[Keyboard.RIGHT_SQUARE] = (Keyboard.BACK_SLASH, False)
normal[Key.caps_lock.value.vk] = (Keyboard.DASH, False)
normal[Keyboard.A] = (Keyboard.A, False)
normal[Keyboard.S] = (Keyboard.O, False)
normal[Keyboard.D] = (Keyboard.E, False)
normal[Keyboard.F] = (Keyboard.I, False)
normal[Keyboard.G] = (Keyboard.U, False)
normal[Keyboard.H] = (Keyboard.D, False)
normal[Keyboard.J] = (Keyboard.H, False)
normal[Keyboard.K] = (Keyboard.T, False)
normal[Keyboard.L] = (Keyboard.N, False)
normal[Keyboard.SEMICOLON] = (Keyboard.S, False)
normal[Keyboard.APOSTROPHE] = (Keyboard.DASH, True)
normal[Keyboard.Z] = (Keyboard.SEMICOLON, False)
normal[Keyboard.X] = (Keyboard.Q, False)
normal[Keyboard.C] = (Keyboard.J, False)
normal[Keyboard.V] = (Keyboard.K, False)
normal[Keyboard.B] = (Keyboard.X, False)
normal[Keyboard.N] = (Keyboard.B, False)
normal[Keyboard.M] = (Keyboard.M, False)
normal[Keyboard.COMMA] = (Keyboard.W, False)
normal[Keyboard.DOT] = (Keyboard.V, False)
normal[Keyboard.FORWARD_SLASH] = (Keyboard.Z, False)

shifted = Keyboard._NORMAL_LAYOUT[Keyboard.MOD_SHIFT]
shifted[Keyboard.GRAVE] = (Keyboard.GRAVE, False)
shifted[Keyboard.ONE] = (Keyboard.ONE, False)
shifted[Keyboard.TWO] = (Keyboard.TWO, False)
shifted[Keyboard.THREE] = (Keyboard.THREE, False)
shifted[Keyboard.FOUR] = (Keyboard.FOUR, False)
shifted[Keyboard.FIVE] = (Keyboard.FIVE, False)
shifted[Keyboard.SIX] = (Keyboard.SIX, False)
shifted[Keyboard.SEVEN] = (Keyboard.SEVEN, False)
shifted[Keyboard.EIGHT] = (Keyboard.EIGHT, False)
shifted[Keyboard.NINE] = (Keyboard.NINE, False)
shifted[Keyboard.ZERO] = (Keyboard.ZERO, False)
shifted[Keyboard.DASH] = (Keyboard.SIX, True)
shifted[Keyboard.EQUAL] = (Keyboard.GRAVE, True)
shifted[Keyboard.Q] = (Keyboard.APOSTROPHE, True)
shifted[Keyboard.W] = (Keyboard.FORWARD_SLASH, True)
shifted[Keyboard.E] = (Keyboard.ONE, True)
shifted[Keyboard.R] = (Keyboard.P, True)
shifted[Keyboard.T] = (Keyboard.Y, True)
shifted[Keyboard.Y] = (Keyboard.F, True)
shifted[Keyboard.U] = (Keyboard.G, True)
shifted[Keyboard.I] = (Keyboard.C, True)
shifted[Keyboard.O] = (Keyboard.R, True)
shifted[Keyboard.P] = (Keyboard.L, True)
shifted[Keyboard.LEFT_SQUARE] = (Keyboard.FIVE, True)
shifted[Keyboard.RIGHT_SQUARE] = (Keyboard.TWO, True)
shifted[Key.caps_lock.value.vk] = (Keyboard.EQUAL, True)
shifted[Keyboard.A] = (Keyboard.A, True)
shifted[Keyboard.S] = (Keyboard.O, True)
shifted[Keyboard.D] = (Keyboard.E, True)
shifted[Keyboard.F] = (Keyboard.I, True)
shifted[Keyboard.G] = (Keyboard.U, True)
shifted[Keyboard.H] = (Keyboard.D, True)
shifted[Keyboard.J] = (Keyboard.H, True)
shifted[Keyboard.K] = (Keyboard.T, True)
shifted[Keyboard.L] = (Keyboard.N, True)
shifted[Keyboard.SEMICOLON] = (Keyboard.S, True)
shifted[Keyboard.APOSTROPHE] = (Keyboard.BACK_SLASH, True)
shifted[Keyboard.Z] = (Keyboard.SEMICOLON, True)
shifted[Keyboard.X] = (Keyboard.Q, True)
shifted[Keyboard.C] = (Keyboard.J, True)
shifted[Keyboard.V] = (Keyboard.K, True)
shifted[Keyboard.B] = (Keyboard.X, True)
shifted[Keyboard.N] = (Keyboard.B, True)
shifted[Keyboard.M] = (Keyboard.M, True)
shifted[Keyboard.COMMA] = (Keyboard.W, True)
shifted[Keyboard.DOT] = (Keyboard.V, True)
shifted[Keyboard.FORWARD_SLASH] = (Keyboard.Z, True)

Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.ONE] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.TWO] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.THREE] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.FOUR] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.FIVE] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.SIX] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.SEVEN] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.EIGHT] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.NINE] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.ZERO] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.R] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.T] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.Y] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.U] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.I] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.O] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.P] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.A] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.S] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.D] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.F] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.G] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.H] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.J] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.K] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.L] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.SEMICOLON] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.X] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.C] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.V] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.B] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.N] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.M] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.COMMA] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.DOT] = True
Keyboard._IS_KEY_SHIFT_LOCKED[Keyboard.FORWARD_SLASH] = True

# MODIFIER AND SPECIAL KEY LAYOUT ##############################################


